#!/bin/bash
#SBATCH -n 4 # Number of cores
#SBATCH --mem 1000 # 2GB solicitados.
#SBATCH -p mhigh,mlow # or mlow Partition to submit to master low prioriy queue
#SBATCH --gres gpu:1 # Para pedir Pascales MAX 8
#SBATCH -o logs/%x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e logs/%x_%u_%j.err # File to which STDERR will be written

python train.py \
--logtostderr \
--training_number_of-steps=1000 \
--train_split="train_fine" \
--model_variant="xception_71" \
--atrous_rates=6 \
--atrous_rates=12 \
--atrous_rates=18 \
--output_stride=16 \
--add_image_level_feature=False \
--decoder_output_stride=4 \
--train_crop_size='769,769' \
--train_batch_size=1 \
--dataset='cityscapes' \
--tf_initial_checkpoint="./datasets/cityscapes/checkpoints/xception_71/model.ckpt" \
--train_logdir="./datasets/cityscapes/exp/train_on_train_set/train/exp4" \
--dataset_dir="./datasets/cityscapes/tfrecord" \
